### ISSUE TITLE
Docker images for production (gocd server)

### ISSUE THREAD

**Issue by savar** [gocd/gocd-docker#1]
Hi,
wouldn't it be easy and useful to enable persistency (volumes) to the docker image(s) so that someone could use it easily for production use case?

At the moment I would take the image as a base image and add the volume functionallity on top of it.

Any suggestion?

Cheers
Simon

**Comment by arvindsv** [comment]
Hello Simon,

Can you take a look at the tag 14.4.0-2 I pushed just now? It has /etc/go, /var/lib/go-server and /var/log/go-server exposed as volumes, and it can be used with a data-only container. If you try it and you think it makes sense, I can make tag it "latest".

Cheers,
Aravind

PS: The diff is going to be:

``` diff
diff --git a/Dockerfile.gocd-server b/Dockerfile.gocd-server
index 7424bda..8c318b1 100644
--- a/Dockerfile.gocd-server
+++ b/Dockerfile.gocd-server
@@ -13,8 +13,14 @@ ADD gocd-server/go-server-start.sh /etc/service/go-server/run

 ADD http://download.go.cd/gocd-deb/go-server-14.4.0-1356.deb /tmp/go-server.deb

+RUN ["groupadd", "-r", "go"]
+RUN ["useradd", "-r", "-c", "Go User", "-g", "go", "-d", "/var/go", "-m", "-s", "/bin/bash", "go"]
+RUN ["mkdir", "-p", "/var/lib/go-server", "/var/log/go-server", "/etc/go"]
+RUN ["chown", "-R", "go:go", "/var/lib/go-server", "/var/log/go-server", "/etc/go"]
+VOLUME ["/var/lib/go-server", "/var/log/go-server", "/etc/go"]
+
 WORKDIR /tmp
-RUN dpkg -i /tmp/go-server.deb
+RUN dpkg -i --debug=10 /tmp/go-server.deb
 RUN sed -i -e 's/DAEMON=Y/DAEMON=N/' /etc/default/go-server
 EXPOSE 8153 8154

```

**Comment by savar** [comment]
Hey Aravind,

thanks for that.. I will check that as soon as I have time for it. Thanks for the fast change!!!

Cheers
Simon

**Comment by savar** [comment]
Looks good to me.. it works like expected.. would be great to have it in an official version :)..

**Comment by arvindsv** [comment]
Done. 14.4.0-2 (86f25f40b8b0) is tagged "latest".
