### ISSUE TITLE
Go Server killed in the middle of executing tasks on agents on different machine due to insufficient heap

### ISSUE THREAD

**Issue by faizhasim** [gocd/gocd-docker#29]
I was monitoring `docker logs` on the `go-server`, while running one of the jobs. Then, I saw this:

```
/etc/init.d/go-server: line 38:    28 Killed                  /usr/share/go-server/server.sh


Error starting Go Server.
```

I'm just wondering if anyone else stumble into similar issue and if there's any way that we can fix this? Thanks.

**Comment by faizhasim** [comment]
Further inspection reveals the root cause.

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000daab0000, 117444608, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 117444608 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/lib/go-server/hs_err_pid938.log
Error starting Go Server.
```

I was running gocd-server on t2.micro on AWS with 1GB ram. From `/usr/share/go-server/server.sh`, default max heap for JVM is set to 1GB. It's good to know some of the JVM parameters are exposed as system environments, thus you can manipulate it from docker env.

**Comment by xgt001** [comment]
Thanks for this @faizhasim , faced the same issue, freeing some ram fixed this.
