### ISSUE TITLE
gocd-server and gocd-agent missing hg binary

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd-docker#30]
Out of the box, GoCD supports Git and Mercurial source code repositories. However, the latest versions of the docker images doesn't contain a `hg` binary, so in practice Mercurial repos can't be used out of the box.

**Comment by ketan** [comment]
Submit a PR against [this line](https://github.com/gocd/gocd-docker/blob/master/Dockerfile.gocd-server#L6)?

**Comment by ketan** [comment]
Might also want to throw in subversion for good measure. I don't know if the perforce binary is distributable.
