### ISSUE TITLE
Use latest version of GoCD

### ISSUE THREAD

**Issue by chrislovsund** [gocd/gocd-docker#32]
16.4.0 is out

**Comment by arvindsv** [comment]
I hear @zabil is automating this so that this will never happen ... :)

**Comment by zabil** [comment]
Yes, don't want to push it manually anymore.
Please give us sometime to get this automated.

**Comment by FredrikWendt** [comment]
+1

**Comment by zabil** [comment]
The images are updated now.

But I am still in the process of setting up a snap pipeline to run the scripts. 
Will close this issue after that's done.
