### ISSUE TITLE
Server does not start with empty mounted directories (/var/lib/go-server /var/log/ ...etc)

### ISSUE THREAD

**Issue by eciuca** [gocd/gocd-docker#40]
ubuntu@ubuntu-xenial:~/dev-env-setup$ docker logs -f linux_gocd-server_1
**\* Running /etc/rc.local...
**\* Booting runit daemon...
**\* Runit started as PID 7
Starting Go Server ...
[Thu Jun 16 09:41:55 UTC 2016] using default settings from /etc/default/go-server
/usr/share/go-server/server.sh: line 180: /var/log/go-server/go-server.out.log: Permission denied
/usr/share/go-server/server.sh: line 181: /var/log/go-server/go-server.out.log: Permission denied
Jun 16 09:41:55 82e1892ae7d1 syslog-ng[15]: syslog-ng starting up; version='3.5.3'
Error trying to validate file agent-bootstrapper.jar: java.io.FileNotFoundException: /var/lib/go-server/agent-bootstrapper.jar (Permission denied)
Error trying to validate file agent.jar: java.io.FileNotFoundException: /var/lib/go-server/agent.jar (Permission denied)
Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /var/lib/go-server/agent-launcher.jar (Permission denied)
Error trying to validate file cruise.war: java.io.FileNotFoundException: /var/lib/go-server/cruise.war (Permission denied)
Error trying to validate file historical_jars/h2-1.2.127.jar: java.io.FileNotFoundException: /var/lib/go-server/historical_jars/h2-1.2.127.jar (No such file or directory)
Error trying to validate file cruise-config.xml: java.io.FileNotFoundException: /etc/go/cruise-config.xml (Permission denied)
Error trying to validate file config.properties: java.io.FileNotFoundException: /etc/go/config.properties (Permission denied)
Error trying to validate file cruise-config.xsd: java.io.FileNotFoundException: /etc/go/cruise-config.xsd (Permission denied)
Error trying to validate file jetty.xml: java.io.FileNotFoundException: /etc/go/jetty.xml (Permission denied)
Error trying to validate file go_update_server.pub: java.io.FileNotFoundException: /etc/go/go_update_server.pub (Permission denied)
/var/lib/go-server/db/h2deltas/2_create_indexes.sql (No such file or directory)
/var/lib/go-server/db/h2db/cruise.h2.db (No such file or directory)
Error trying to validate file log4j.properties: java.io.FileNotFoundException: /etc/go/log4j.properties (Permission denied)
== Thu Jun 16 09:42:26 UTC 2016: Waiting for Go Server dashboard to be accessible ...
Error starting Go Server.
== Thu Jun 16 09:42:56 UTC 2016: Waiting for Go Server dashboard to be accessible ...
== Thu Jun 16 09:43:27 UTC 2016: Waiting for Go Server dashboard to be accessible ...
== Thu Jun 16 09:43:57 UTC 2016: Waiting for Go Server dashboard to be accessible ...
== Thu Jun 16 09:44:28 UTC 2016: Waiting for Go Server dashboard to be accessible ...

Is there no way to do this without copying the files from inside the container?

**Comment by eciuca** [comment]
I had to create the go user and group and chown the volumes. Is there any other way?

**Comment by eciuca** [comment]
Hi! I solved it by using a named volume in docker compose.

```
version: "2"
volumes:
  gocd-server-volume: {}

services:
  gocd-server:
    image: gocd/gocd-server
    ports:
     - "8153:8153"
    volumes:
     - gocd-server-volume:/etc/go
     - gocd-server-volume:/var/lib/go-server
     - gocd-server-volume:/var/log/go-server
```

**Comment by ketan** [comment]
Marking closed. Do you think there's scope to update the README with better instructions?

**Comment by eciuca** [comment]
Yes. Instead of telling users to use data-only container the README should say that they should use named volumes because that is the easiest way to do it (and the appropiate one I think) and you don't have to create a container.

`docker run -d -i -t -p 8155:8153 -v gocd-server-volume:/var/lib/go-server -v gocd-server-volume:/var/log/go-server -v gocd-server-volume:/etc/go gocd/gocd-server`

The reason is that when you use docker-compose volumes mapped directly to host the owner of the mounted folders is the same as the one in the host. When you use named volumes (as I did in the previous comment) this problem is solved because the folders are still owned by the right user (the user under which the container is ran).

I had this problem also because I'm new to docker and I didn't know how named volumes worked.
