### ISSUE TITLE
use GO_SERVER_URL not GO_SERVER fo gocd-agent

### ISSUE THREAD

**Issue by EugenMayer** [gocd/gocd-docker#51]
since GO_SERVER is deprecated GO_SERVER_URL should be used or at least supported

**Comment by arvindsv** [comment]
Looks like this is [done](https://github.com/gocd/gocd-docker/blob/92d9a2b17c321494d611fc86fee5e1b44ab32ba3/phusion/agent/go-agent-start.sh#L10).
