### ISSUE TITLE
Java 8 (runtime) compatibility

### ISSUE THREAD

**Issue by headcr4sh** [gocd/gocd-docker#68]
## Issue
Plugins that have been compiled using Java 8 byte code (52) as a target won't work with the official GoCD docker image.

## Cause
* The official GoCD Docker Image is based upon an image that still uses OpenJDK 7.
* It is based upon Ubuntu 14.04 LTS release (which might also be a bit old).

## Possible solution
* Upgrade base Docker image to Ubuntu 16.04 LTS
* Install OpenJDK 8

**Comment by zabil** [comment]
Refer 
https://github.com/gocd/gocd-docker/pull/69

Retaining Ubuntu 14.04 LTS
